Webthucpham.AdminApp/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Webthucpham.Api;
using Webthucpham.Data.Enums;
using Webthucpham.ViewModels.Catalog.Categories;
using Webthucpham.ViewModels.Common;

namespace Webthucpham.AdminApp.Controllers
{
    public class CategoryController : BaseController
    {
        private readonly ICategoryApiClient _categoryApiClient;
        private readonly IConfiguration _config;

        public CategoryController(ICategoryApiClient categoryApiClient, IConfiguration configuration)
        {
            _config = configuration;
            _categoryApiClient = categoryApiClient;
        }
        public async Task<IActionResult> Index(string keyword = "", string status = "", int pageSize = 10, int pageIndex = 1)
        {
            var paginateRequest = new PaginateRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };

            var categories = await _categoryApiClient.GetAllPaging(paginateRequest, status);
            ViewBag.Keyword = paginateRequest.Keyword;

            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }

            return View(categories);
        }

        [HttpGet("category/create")]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost("category/create")]
        public async Task<IActionResult> Create(CategoryCreateRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var result = await _categoryApiClient.Create(request);

            if (result > 0)
            {
                TempData["result"] = "Tạo danh mục thành công!";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Tạo danh mục thất bại!");
            return View(request);
        }


        [HttpGet("category/{id}")]
        public async Task<IActionResult> Edit(int id)
        {

            var category = await _categoryApiClient.GetById(id);
            if (category == null)
            {
                return RedirectToAction("Error", "Home");
            }
            var model = new CategoryUpdateRequest() { Id = id, Name = category.Name, IsOutstanding = category.IsOutstanding };
            return View(model);
        }

        [HttpPost("category/{id}")]
        public async Task<IActionResult> Edit(CategoryUpdateRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var result = await _categoryApiClient.Edit(request);

            if (result)
            {
                TempData["result"] = "Cập nhật danh mục thành công";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Cập nhật danh mục thất bại!");
            return View(request);
        }
        [HttpDelete]
        public async Task Delete(int id)
        {

            var category = await _categoryApiClient.GetById(id);
            if (category == null)
            {

                RedirectToAction("Error", "Home");
            }
            else
            {
                var result = await _categoryApiClient.Delete(id);
                if (category.Status == Status.Active)
                {

                    if (result)
                    {
                        TempData["result"] = "Ẩn danh mục thành công";
                        RedirectToAction("Index");
                    }
                    else
                    {

                        TempData["error"] = "Ẩn danh mục thất bại";
                        RedirectToAction("Index");
                    }
                }
                else
                {
                    if (result)
                    {
                        TempData["result"] = "Kích hoạt danh mục thành công";
                        RedirectToAction("Index");
                    }
                    else
                    {

                        TempData["error"] = "kích hoạt danh mục thất bại";
                        RedirectToAction("Index");
                    }
                }

            }
        }
    }
}

Webthucpham.AdminApp/Controllers/Components/ChangePageSizeViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Webthucpham.ViewModels.Common;

namespace Webthucpham.AdminApp.Controllers.Components
{
    public class ChangePageSizeViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PageResponseBase request)
        {
            return Task.FromResult((IViewComponentResult)View("ChangePageSize", request));
        }

    }
}

Webthucpham.AdminApp/Controllers/Components/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Webthucpham.ViewModels.Common;

namespace Webthucpham.AdminApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

Webthucpham.AdminApp/Views/Category/Create.cshtml
@model Webthucpham.ViewModels.Catalog.Categories.CategoryCreateRequest

@{
    ViewData["Title"] = "Tạo danh mục";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <h1 class="mt-4">Danh mục</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Category">Danh sách danh mục</a></li>
        <li class="breadcrumb-item active">Tạo mới danh mục</li>
    </ol>

    <div class="card mb-4">
        <div class="card-header d-flex justify-content-between">
            <a asp-action="Index" asp-controller="Category" class="btn btn-outline-dark"><i class="fas fa-chevron-left back-list-product mr-2"></i>Quay lại danh sách danh mục</a>

        </div>
        <div class="card-body">
            <div>
                <form asp-action="Create" class="d-flex flex-column">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label class="control-label">Tên danh mục: </label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="form-group d-flex justify-content-between">
                        <input type="submit" value="Tạo mới" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Webthucpham.AdminApp/Views/Category/Edit.cshtml
@model Webthucpham.ViewModels.Catalog.Categories.CategoryUpdateRequest

@{
    ViewData["Title"] = "Cập nhật danh mục";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h1 class="mt-4">Danh mục</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Category">Danh sách danh mục</a></li>
        <li class="breadcrumb-item active">Cập nhật danh mục</li>
    </ol>

    <div class="card mb-4">
        <div class="card-header d-flex justify-content-between">
            <a asp-action="Index" asp-controller="Category" class="btn btn-outline-dark"><i class="fas fa-chevron-left back-list-product mr-2"></i>Quay lại danh sách danh mục</a>
            <div>
                <label class="m-0 btn btn-outline-dark d-flex align-items-center justify-content-center" for="updateCategoryBtn">
                    <i class="far fa-save mr-2"></i>
                    Lưu
                </label>
            </div>
        </div>
        <div class="card-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <form asp-action="Edit" id="editCategoryForm" method="post" asp-controller="Category">
                <input asp-for="Id" type="hidden" class="form-control" />
                <div class="row">

                <div class="col-6 form-group">
                    <label asp-for="Name" class="control-label">Tên Danh Mục</label>
                    <input asp-for="Name" id="categoryName" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                
                <div class="col-6 form-group">
                    <label asp-for="IsOutstanding" class="control-label">Hiển thị trang chủ</label>
                    <input asp-for="IsOutstanding" id="categoryIsOutstanding" type="checkbox" class="form-control outline-none mt-1" style="width:28px;height:28px" />
                </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="" id="updateCategoryBtn" class="d-none btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

Webthucpham.AdminApp/Views/Category/Index.cshtml
@using Webthucpham.ViewModels.Common;
@using Webthucpham.Data.Enums;
@model PageResponse<Webthucpham.ViewModels.Catalog.Categories.CategoryViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
<div class="container-fluid">
    <h1 class="mt-4">Danh Mục</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Bảng Điều Khiển</a></li>
        <li class="breadcrumb-item active">Danh Sách Danh Mục</li>
    </ol>

    <div class="card mb-12">
        <div class="card-header d-flex justify-content-between">
            <form asp-action="Index" method="get">
                <div class="form-outline mb-4 d-flex">
                    <input name="keyword" value="@ViewBag.Keyword" type="text" id="categorySearchBox" placeholder="Tìm kiếm..." class="form-control  border-dark" />
                    <input asp-for="PageSize" value="@Model.PageSize" type="hidden" />
                    <button type="submit" class="btn btn-outline-dark ml-2">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
                <div class="form-group d-flex flex-column mb-0 mt-3">
                    <span class="m-1">Lọc theo trạng thái danh mục :</span>
                    <div class="order_button d-flex ">
                        <button name="status" value="Active" class="btn btn-outline-secondary mr-2" style="min-width:140px">Đang hoạt động</button>
                        <button name="status" value="InActive" class="btn btn-outline-secondary mr-1 ml-1" style="min-width:140px">Dừng hoạt động</button>
                    </div>
                </div>
            </form>

            <div>
                <a asp-action="Create" asp-controller="Category" class="btn btn-outline-dark ">
                    <i class="fas fa-plus mr-2"></i>
                    Tạo Danh Mục Mới
                </a>
            </div>

        </div>
        <div class="card-body">
            @if (ViewBag.SuccessMsg != null)
            {
                <div class="d-flex justify-content-center">
                    <div id="msgAlert" class="alert alert-success w-25" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                </div>
            }
            <div class="d-flex w-25 align-items-center mb-3">
                @await Component.InvokeAsync("ChangePageSize", Model)
            </div>
            <div class="table-responsive">
                <table class="table table-bordered border-dark text-center">
                    <thead class="thead-dark text-white">
                        <tr class="bg-alternating d-flex">
                            <th scope="col" style="flex:0.1">
                                Id
                            </th>
                            <th scope="col" style="flex:1">
                                Tên
                            </th>
                            <th scope="col" style="flex:0.3">
                                Trang chủ
                            </th>
                            <th style="flex: 0.4" scope="col">
                                Tác Vụ
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr class="bg-alternating d-flex">
                                <td style="flex:0.1">
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td style="flex:1">
                                    @if (item.Status != Status.InActive)
                                    {
                                        <a href="#" onclick="editCategory(@item.Id)">
                                            @item.Name
                                        </a>
                                    }
                                    else
                                    {
                                        <span class="disabled">
                                            @item.Name
                                        </span>
                                    }
                                </td>
                                <td style="flex:0.3">

                                    @if (item.IsOutstanding)
                                    {
                                        <input type="checkbox" disabled class="btn-checkbox" checked="@item.IsOutstanding" onclick="getCategoryId(@item.Id)" style="width:20px;height:20px" data-target="#changeIOSCategoryModal" data-toggle="modal" />
                                    }
                                    else
                                    {
                                        <input type="checkbox" disabled class="btn-checkbox" checked="@item.IsOutstanding" onclick="getCategoryId(@item.Id)" style="width:20px;height:20px" data-target="#changeIOSCategoryModal" data-toggle="modal" />
                                    }
                                </td>
                                <td class="d-flex align-items-center justify-content-center" style="flex: 0.4">
                                    @if (item.Status != Status.InActive)
                                    {
                                        <span class="actions-btn">
                                            <span id="editCategoryBtn" onclick="editCategory(@item.Id)" class="btn btn-outline-info">Sửa</span>
                                        </span>

                                        <span class="actions-btn ml-2">
                                            <button onclick="getValue(@item.Id)" data-target="#deleteCategoryModal" data-toggle="modal" class="btn btn-outline-danger">
                                                Xóa
                                            </button>
                                        </span>

                                    }
                                    else
                                    {
                                        <span class="actions-btn ml-2">
                                            <button onclick="getValue(@item.Id)" data-target="#activeCategoryModal" data-toggle="modal" class="btn btn-outline-danger">
                                                Kích hoạt
                                            </button>
                                        </span>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            @await Component.InvokeAsync("Pager", Model)
            <div class="modal fade" id="changeIOSCategoryModal" tabindex="-1" role="dialog" aria-labelledby="changeIOSCategoryTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteCategoryTitle">Thay đổi hiện trạng danh mục </h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Bạn có chắc chắn muốn thay đổi hiện trạng danh mục này?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                            <button type="submit" class="btn btn-success" data-dismiss="modal" id="change_submit_btn">Sửa</button>

                        </div>
                    </div>
                </div>
            </div>

            <!-- Button trigger modal -->
            <!-- Modal -->
            <div class="modal fade" id="deleteCategoryModal" tabindex="-1" role="dialog" aria-labelledby="deleteCategoryTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteCategoryTitle">Xóa danh mục</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Bạn có chắc chắn muốn xóa danh mục này?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                            <button type="submit" class="btn btn-danger" data-dismiss="modal" id="delete_submit_btn">Xóa</button>

                        </div>
                    </div>
                </div>
            </div>
            @*Modal*@
            <div class="modal fade" id="activeCategoryModal" tabindex="-1" role="dialog" aria-labelledby="activeCategoryTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="activeCategoryTitle">Kích hoạt danh mục</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Bạn có chắc chắn muốn kích hoạt danh mục này?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                            <button type="submit" class="btn btn-danger" data-dismiss="modal" id="active_submit_btn">Kích hoạt</button>

                        </div>
                    </div>
                </div>
            </div>
            @*End*@

        </div>
    </div>
</div>

@section Scripts{
    <script>
        const editCategory = (categoryId) => window.location.assign(`category/${categoryId}`)
    </script>
    <script>
        setTimeout(() => $('#msgAlert').fadeOut('slow'), 1500)
    </script>
    <script>
        var delete_id = -1;
        const getValue = (id) => delete_id = id;
        $('#delete_submit_btn').on('click', () => {
            $.ajax(
                {
                    type: "delete",
                    url: `category/delete/`,
                    dataType: "text",
                    data: { id: delete_id },
                    async: true,
                    success: function (response) {
                        location.reload();
                    },
                    failure: function (response) {
                        alert('false')
                    },
                    error: function (response) {
                        alert('error')
                    }
                });
        });
        $('#active_submit_btn').on('click', () => {
            $.ajax(
                {
                    type: "delete",
                    url: `category/delete/`,
                    dataType: "text",
                    data: { id: delete_id },
                    async: true,
                    success: function (response) {
                        location.reload();
                    },
                    failure: function (response) {
                        alert('false')
                    },
                    error: function (response) {
                        alert('error')
                    }
                });
        })

    </script>

<script>
        var change_id = -1;
    const getCategoryId = (id) => change_id = id;
    $('#change_submit_btn').on('click', () => {
            $.ajax(
                {
                    type: "POST",
                    url: `category/${change_id}`,
                    dataType: "text",
                    data: { id: change_id },
                    async: true,
                    success: function (response) {
                        location.reload();
                    },
                    failure: function (response) {
                        alert('false')
                    },
                    error: function (response) {
                        alert('error')
                    }
                });
        })

    </script>
   
    
}