Webthucpham.AdminApp/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Webthucpham.Api;
using Webthucpham.ViewModels.System.Clients;

namespace Webthucpham.AdminApp.Controllers
{
    public class ClientController : BaseController
    {
        private readonly IClientApi _clientApi;
        private readonly IClientOrderApi _clientOrderApi;
        private readonly IConfiguration _config;

        public ClientController(IClientApi clientApi, IClientOrderApi clientOrderApi,
            IConfiguration config
         )
        {
            _clientApi = clientApi;
            _clientOrderApi = clientOrderApi;
            _config = config;
        }
        public async Task<IActionResult> Index(string keyword = "", int pageIndex = 1, int pageSize = 10)
        {

            var request = new GetClientPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize,
            };

            var data = await _clientApi.GetClientPaging(request);
            ViewBag.Keyword = keyword;
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(data.ResultObj);
        }

        [HttpGet("client/{id}/details")]
        public async Task<IActionResult> Details(string id)
        {
            var client = await _clientApi.GetByClientId(new Guid(id));
            var order = await _clientApi.GetOrderByClientId(new Guid(id));
            client.Orders = order;
            return View(client);
        }


        [HttpPut]
        public async Task<JsonResult> cancelOrder(int orderId, string cancelReason)
        {

            var result = await _clientOrderApi.ClientCancelOrder(orderId, cancelReason);

            return new JsonResult(new { message = result.Message, isSuccess = result.IsSuccessed });
        }
    }
}

Webthucpham.AdminApp/Controllers/Components/ChangePageSizeViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Webthucpham.ViewModels.Common;

namespace Webthucpham.AdminApp.Controllers.Components
{
    public class ChangePageSizeViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PageResponseBase request)
        {
            return Task.FromResult((IViewComponentResult)View("ChangePageSize", request));
        }

    }
}

Webthucpham.AdminApp/Controllers/Components/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Webthucpham.ViewModels.Common;

namespace Webthucpham.AdminApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

Webthucpham.AdminApp/Views/Client/Index.cshtml
@using Webthucpham.ViewModels.Common;
@model PageResponse<Webthucpham.ViewModels.System.Clients.ClientViewModel>;
@using Webthucpham.ViewModels.System.Clients;

@{
    ViewData["Title"] = "Danh Sách Khách Hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@section Scripts{
    <script>
        setTimeout(() => $('#msgAlert').fadeOut('slow'), 1500)
    </script>
}

<div class="container-fluid">
    <h1 class="mt-4">Khách Hàng</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Bảng Điều Khiển</a></li>
        <li class="breadcrumb-item active">Danh Sách Khách Hàng</li>
    </ol>

    <div class="card mb-12">
        <div class="card-header d-flex justify-content-between">
            <form asp-action="Index" method="get">
                <div class="form-outline mb-4 d-flex">
                    <input name="keyword" value="@ViewBag.Keyword" type="text" id="userSearchBox" placeholder="Tìm kiếm..." class="form-control  border-dark" />
                    <input asp-for="PageSize" value="@Model.PageSize" type="hidden" />
                    <button type="submit" class="btn btn-outline-dark ml-2">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>


        </div>
        <div class="card-body">
            @if (ViewBag.SuccessMsg != null)
            {
                <div class="d-flex justify-content-center">
                    <div id="msgAlert" class="alert alert-success w-25" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                </div>
            }
            <div class="d-flex w-25 align-items-center mb-3">
                @await Component.InvokeAsync("ChangePageSize", Model)
            </div>
            <div class="table-responsive">

                <table class="table table-bordered text-center">
                    <thead class="thead-dark text-white">
                        <tr>
                            <th>
                                STT
                            </th>
                            <th>
                                Tên
                            </th>
                            <th>
                                Email
                            </th>
                            <th>
                                Địa Chỉ
                            </th>
                            <th>
                                Ngày Sinh
                            </th>
                            <th>
                                Số Điện Thoại
                            </th>
                            <th>
                                Số Đơn Hàng
                            </th>
                            <th>
                                Tác Vụ
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (var count = 0; count < Model.Items.Count; count++)
                        {

                            <tr class="bg-alternating ">
                                <td>@(count + 1)</td>
                                <td>
                                    @Html.ActionLink(Model.Items[count].Name, "Details", new { id = Model.Items[count].Id })
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => Model.Items[count].Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => Model.Items[count].Address)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => Model.Items[count].Dob)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => Model.Items[count].PhoneNumber)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => Model.Items[count].OrderQuanttity)
                                </td>
                                <td class="btn-edit_del">
                                    <a href="@Url.Action("Details","Client",  new { id = Model.Items[count].Id })" class="p-1 btn actions-btn btn-outline-info px-2">
                                        Chi Tiết
                                    </a>
                                </td>

                            </tr>
                        }


                    </tbody>
                </table>
            </div>

            @await Component.InvokeAsync("Pager", Model)
        </div>
    </div>
</div>