Webthucpham.AdminApp/Controllers/ProductImageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Webthucpham.Api;
using Webthucpham.ViewModels.Catalog.ProductImages;

namespace Webthucpham.AdminApp.Controllers
{
    public class ProductImageController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        public ProductImageController(IProductApiClient productApiClient)
        {
            _productApiClient = productApiClient;
        }

        [HttpGet("product/images/{imageId}/edit")]
        public async Task<IActionResult> Edit(int imageId, [FromQuery] int productId)
        {

            if (!ModelState.IsValid || imageId == 0 || productId == 0)
            {
                return RedirectToAction("Error", "Home");
            }
            var image = await _productApiClient.GetImageById(productId, imageId);
            if (image == null)
            {
                return RedirectToAction("Error", "Home");
            }
            var model = new ProductImageUpdateRequest()
            {
                Id = imageId,
                ProductId = productId,
                Caption = image.Caption
            };
            return View(model);
        }

        [HttpPost("product/images/{imageId}/edit")]
        public async Task<IActionResult> Edit(ProductImageUpdateRequest request)
        {

            if (!ModelState.IsValid || request.Id == 0)
            {
                return View(request);
            }
            var result = await _productApiClient.UpdateProductImage(request);
            if (!result)
                return View(request);
            TempData["result"] = "Sửa ảnh thành công!";
            return LocalRedirect($"/Product/{request.ProductId}/images");
        }
        [HttpDelete("product/{productId}/images")]
        public async Task Delete(int productId, [FromQuery] int imageId)
        {

            if (!ModelState.IsValid || productId < 1 || imageId < 1)
            {

                LocalRedirect($"/Product/{productId}/images");
            }
            var result = await _productApiClient.DeleteImage(productId, imageId);
            if (!result.IsSuccessed || !result.ResultObj)
            {
                TempData["error"] = result.Message;
                LocalRedirect($"/Product/{productId}/images");
            }
            else
            {
                TempData["result"] = result.Message;
                LocalRedirect($"/Product/{productId}/images");
            }
        }

        [HttpGet("product/{productId}/images/add")]
        public IActionResult Add(int productId)
        {

            if (!ModelState.IsValid || productId == 0)
            {
                return RedirectToAction("Error", "Home");
            }

            var model = new ProductImageCreateRequest()
            {
                ProductId = productId
            };
            return View(model);
        }

        [HttpPost("product/{productId}/images/add")]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Add(ProductImageCreateRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }


            var result = await _productApiClient.AddImage(request);

            if (!result)
            {
                return View(request);
            }

            TempData["result"] = "Thêm ảnh thành công!";
            return LocalRedirect($"/Product/{request.ProductId}/images");
        }

    }
}

Webthucpham.AdminApp/Views/ProductImage/Add.cshtml
@model Webthucpham.ViewModels.Catalog.ProductImages.ProductImageCreateRequest

@{
    ViewData["Title"] = "Thêm ảnh cho sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@section Scripts{
    <script type="text/javascript">
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
    <script type="text/javascript">
        $('#customFile').change((e) => {
            if (e.target.files && e.target.files[0]) {
                var ImageDir = new FileReader();
                ImageDir.onload = (a) => {
                    $('#impPrev').attr('src', a.target.result);
                }
                ImageDir.readAsDataURL(e.target.files[0]);
            }
        })
    </script>

    <script>

        const redirectToAction = () => {
            const productImages = '/product/@Model.ProductId/images';
            return window.location.assign(productImages)
        }
    </script>
}
<div class="container-fluid">
    <h1 class="mt-4">Ảnh sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="#" onclick="redirectToAction()">Danh sách ảnh sản phẩm</a></li>
        <li class="breadcrumb-item active">Thêm ảnh mới</li>
    </ol>

    <div class="card mb-4">
        <div class="card-header d-flex justify-content-between">
            <div>
                <a href="#" onclick="redirectToAction()" class="btn btn-outline-dark"><i class="fas fa-chevron-left back-list-product mr-2"></i>Quay lại </a>
            </div>
            <label for="add-product-image-btn" class="btn btn-outline-dark px-4">
                <i class="fas fa-plus mr-2"></i>
                Tạo mới
            </label>
        </div>
        <div class="card-body">
            <div>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <form asp-controller="ProductImage" method="post" asp-action="Add" enctype="multipart/form-data">
                    <div class="form-group">

                        <input asp-for="ProductId" class="form-control" type="hidden" />
                    </div>
                    <div class="form-group">
                        <label class="control-label">Chú thích</label>
                        <input placeholder="Nhập chú thích" type="text" asp-for="Caption" class="form-control" />
                        <span asp-validation-for="Caption" class="text-danger"></span>
                    </div>
                    <div class="w-100 justify-content-end">
                        <div class="form-group">
                            <label class="control-label">Ảnh</label>
                            <div class="custom-file">
                                <input asp-for="ImageFile" accept="image/*" class="custom-file-input" id="customFile">
                                <label class="custom-file-label" for="customFile">Chọn ảnh</label>
                            </div>
                            <span asp-validation-for="ImageFile" class="text-danger"></span>
                        </div>
                        <div>
                            <img id="impPrev" class="mw-100" style="height:auto" />
                        </div>
                    </div>
                    <input class="d-none" type="submit" id="add-product-image-btn" />
                </form>
            </div>
        </div>
    </div>
</div>

Webthucpham.AdminApp/Views/ProductImage/Edit.cshtml
@model Webthucpham.ViewModels.Catalog.ProductImages.ProductImageUpdateRequest

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    <script type="text/javascript">
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
    <script type="text/javascript">
        $('#customFile').change((e) => {
            if (e.target.files && e.target.files[0]) {
                var ImageDir = new FileReader();
                ImageDir.onload = (a) => {
                    $('#impPrev').attr('src', a.target.result);
                }
                ImageDir.readAsDataURL(e.target.files[0]);
            }
        })
    </script>

    <script>
        const productImages = '/product/@Model.ProductId/images';
        const redirectToAction = () => window.location.assign(productImages)

    </script>
}
<div class="container-fluid">
    <h1 class="mt-4">Ảnh sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="#" onclick="redirectToAction()">Danh sách ảnh sản phẩm</a></li>
        <li class="breadcrumb-item active">Sửa ảnh</li>
    </ol>

    <div class="card mb-4">
        <div class="card-header d-flex justify-content-between">
            <div>
                <a href="#" onclick="redirectToAction()" class="btn btn-outline-dark"><i class="fas fa-chevron-left back-list-product mr-2"></i>Quay lại </a>
            </div>
            <label for="submitSaveProductI" class="btn btn-outline-dark px-4">
                <i class="far fa-save mr-2"></i>
                Lưu lại
            </label>
        </div>
        <div class="card-body">
            <div>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <form asp-action="Edit" enctype="multipart/form-data">
                    <input asp-for="Id" type="hidden" class="form-control" />
                    <input asp-for="ProductId" type="hidden" class="form-control" />
                    <div class="form-group">
                        <label class="control-label">Chú thích</label>
                        <input placeholder="Nhập chú thích" type="text" asp-for="Caption" class="form-control" />
                        <span asp-validation-for="Caption" class="text-danger"></span>
                    </div>
                    <div class="w-100 justify-content-end">
                        <div class="form-group">
                            <label class="control-label">Ảnh</label>
                            <div class="custom-file">
                                <input asp-for="ImageFile" accept="image/*" class="custom-file-input" id="customFile">
                                <label class="custom-file-label" for="customFile">Chọn ảnh</label>
                            </div>
                            <span asp-validation-for="ImageFile" class="text-danger"></span>
                        </div>
                        <div>
                            <img id="impPrev" class="mw-100" style="height:auto" />
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" id="submitSaveProductI" class="d-none" />
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>